name: GitHub Release

concurrency: deployment

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release-me:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    steps:
      # Create an example file
      - run: echo "Example" > output.txt

      # Upload the output file as a build artifact
      - uses: actions/upload-artifact@v3
      with:
        name: output-as-artifact
        path: output.txt

      - name: Run ReleaseMe
        id: release
        uses: dev-build-deploy/release-me@v0
        with:
          token: ${{ github.token }}
          artifacts: output-as-artifact  # Downloads the build artifact and uploads it as a GitHub Release Asset
          files: output.txt              # Uploads the local file as a GitHub Release Asset

      - if: ${{ steps.release.outputs.created }}
        run: echo ${{ fromJSON(steps.release.outputs.release).id }}  # This will provide the newly created GitHub Release ID
